spring:
  datasource:
    url: jdbc:mysql://account-db:3306/account?useSSL=false&useUnicode=true&characterEncoding=utf-8&allowPublicKeyRetrieval=true
    username: user
    password: 123456
  jpa:
    hibernate:
      ddl-auto: create-drop
