spring:
  datasource:
    url: jdbc:mysql://account-db:3306/account?useSSL=false&useUnicode=true&characterEncoding=utf-8&allowPublicKeyRetrieval=true
    username: user
    password: 123456
  jpa:
    hibernate:
      ddl-auto: create-drop

jwt:
  access-token:
    sign:
      key: ${ACCESS_TOKEN_SECRET_KEY}
    expiration: ${ACCESS_TOKEN_EXPIRATION}
  refresh-token:
    sign:
      key: ${REFRESH_TOKEN_SECRET_KEY}
    expiration: ${2592000000}
